spring:
  freemarker:
    cache: false
    settings:
<<<<<<< HEAD
#      auto_import: /_imports/common.ftlh as c
      output_encoding: UTF-8
=======
     auto_import: /_imports/common.ftlh as c
     output_encoding: UTF-8
>>>>>>> cad91fd (Initial commit)
  datasource:
    url: jdbc:h2:file:./data/blog;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;COLLATION=CZECH
    driverClassName: org.h2.Driver
    username: sa
    password: ''
